### ISSUE TITLE
use the Cypher query comments as titles

### ISSUE THREAD

**Issue by peterneubauer** [neo4j-contrib/graphgist#12]
use

```
[source,cypher]
----
//this is the title 
MATCH (n) RETURN n
----
```

As the query title, as in the Neo4j Browser

**Comment by nawroth** [comment]
As there is already an AsciiDoc syntax for this, I think it's much better to go with that. We just have to add styles for it, the HTML is already in place.

```
.this is the title 
[source,cypher]
----
MATCH (n) RETURN n
----
```

**Comment by nawroth** [comment]
Fixed the styling, see http://localhost/gist/?7005107
