### ISSUE TITLE
Question : graph visualisation

### ISSUE THREAD

**Issue by HugoCornu** [neo4j-contrib/graphgist#31]
Hi,
I was wondering what library/plugin do you use for the graph visualisation (where one can mouve the nodes around with the mouse)? It's really awesome

**Comment by jexp** [comment]
We use a fork of the neo4j-browser visualization.

You can find it in the neod3.js and neod3-visualization.js files in the scripts directory.

**Comment by HugoCornu** [comment]
thanks!
