### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by ekkis** [neo4j-contrib/graphgist#34]
I want to run this project within an enterprise environment but I can't figure out what to download and install to make it work.  it seems this project is only meant to be run from github.  any guidance?

**Comment by jexp** [comment]
See here: https://gist.github.com/jexp/70296ce410ff431ddbef

**Comment by jexp** [comment]
Actually I added the script to this repo for convenience
https://github.com/neo4j-contrib/graphgist/blob/gh-pages/install-graphgist.sh

**Comment by ekkis** [comment]
that's cool.  I guess I'll need to install Python!  thanks a bunch

**Comment by ekkis** [comment]
jexp: I followed the instructions in your script and I'm now running graphgist locally, however, the last line:

```
open http://localhost:8000/?http%3A%2F%2Flocalhost%3A8000%2Fgists%2Fmy-graph-use-case.adoc
```

causes my browser to display an error: Not Found, and trying to open this link: `http://localhost:8000/gists/my-graph-use-case.adoc` causes my browser to download a file for which I don't have an associated application.

I must be close.  what am I missing?
